version: '2'
services:
    kong:
      build: .
      ports:
        - 8000:8000
        - 8001:8001
        - 8443:8443
        - 8444:8444
      environment:
        - KONG_DATABASE=off
        - KONG_DECLARATIVE_CONFIG=/tmp/config.yml
        - 'KONG_PROXY_LISTEN=0.0.0.0:8000'
        - KONG_ADMIN_HTTP_PORT_NUMBER=8001
        - KONG_LOG_LEVEL=debug
        - 'KONG_PLUGINS=bundled,num2word'
        - KONG_PLUGINSERVER_NAMES=num2word
        - KONG_PLUGINSERVER_NUM2WORD_START_CMD=/usr/local/bin/num2word
        - 'KONG_PLUGINSERVER_NUM2WORD_QUERY_CMD=/usr/local/bin/num2word -dump'
      volumes:
        - ./config.yml:/tmp/config.yml
